plugins {
}

if (rootProject.file('build-conventions.gradle').exists()) {
	apply from: rootProject.file('build-conventions.gradle')
}

dependencies {
	addModuleDeps('GoldenBoughsLib')
	addJarJarLocalLibs()
}

neoForge {
	runs {
		named('data') {
			gameDirectory = project.file('run-data')
		}
	}
}

addClientAuthRun()

