package architecture.resonator_combat_framework.mixed

import architecture.resonator_combat_framework.module.entity_animation.mixed.IAnimationProxyProvider

interface IPlayerRcf : IAnimationProxyProvider

