[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${ mod_id }]]
modId = "geckolib"
type = "required"
versionRange = "${geckolib_version}"
ordering = "NONE"
side = "BOTH"
